# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11a26608f99eb0508afbf4f6a3ad5d56edd8798911c9e9ee8d37d3dfd387372eb066d50187bf50b399db10f144b1026ef45834a8832ac1ea583be3b4d95e17f

test:
  secret_key_base: 8d813187a5db4f93526f98422822526c8e0f9228fa535d1cb6958bc80470331ebadf9c9ab3c38d42d983a8c53105e1c81409d398b3d3a88b89f577f0a491d0e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
